version: '3'

services:
  ngrok:
    image: gtriggiano/ngrok-tunnel
    hostname: ngrok
    environment:
      - TARGET_HOST=linebot
      - TARGET_PORT=2000
    depends_on:
      - linebot

  linebot:
    image: linebot_helloworld
    build: .
    ports:
      - 2000:2000